#!/bin/bash

# NOTE: Ubuntu 16.04 not fully supporting python3

export DEBIAN_FRONTEND=noninteractive

# install python setuptools
apt-get update -q
apt-get install python3.8
apt-get -y install python3-pip
#apt-get install -qy --no-install-recommends python-setuptools
#apt-get clean
#rm -rf /var/lib/apt/lists/*

# install pip; ignore outputs
#easy_install pip3 &> /dev/null

# install dependencies
pip3 install pandas
pip3 install geopandas
pip3 install numpy
pip3 install altair
